version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: minhaSenhaRoot
      MYSQL_DATABASE: meu_banco_de_dados
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: minhaSenhaUsuario
    ports:
      - "5432:5432"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: